//! Package downloads through a Gradle (Maven repository) mirror with fallback.
//!
//! Gradle has no `install <package>` command: dependencies are resolved from
//! the repositories a build declares. Each mirror is therefore tried with a
//! throwaway project that declares the requested coordinates against that
//! mirror and resolves them, which downloads the artifacts into the shared
//! Gradle cache (Gradle's equivalent of an installed package). The throwaway
//! project is deleted again after each attempt.

use crate::mirror::{load_mirrors, Registry};
use std::fs;
use std::path::Path;
use std::process::Stdio;
use tokio::process::Command;

/// Downloads `args` (Maven coordinates, e.g.
/// `com.google.guava:guava:34.0.0-jre`) via the first configured Gradle
/// mirror that succeeds. Gradle's output streams straight to the terminal; a
/// failed mirror falls through to the next one.
pub async fn install(args: &[String]) -> Result<(), Box<dyn std::error::Error>> {
    if args.is_empty() {
        return Err(
            "No packages given; pass Maven coordinates like group:artifact:version.".into(),
        );
    }

    let config = load_mirrors(Registry::Gradle)?;
    let gradle = resolve_gradle().await?;
    let coordinates: Vec<String> = args.iter().map(|arg| with_version(arg)).collect();

    let mut last_status = String::from("no mirrors configured");
    for mirror in &config.mirrors {
        println!("Installing via {mirror}...");

        let project = temp_project_dir();
        write_project(&project, mirror, &coordinates)?;

        let status = Command::new(gradle)
            .args(["resolveMirror", "--console=plain", "--no-daemon"])
            .current_dir(&project)
            .stdin(Stdio::inherit())
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit())
            .status()
            .await?;

        let _ = fs::remove_dir_all(&project);

        if status.success() {
            println!("Installed successfully via {mirror}.");
            return Ok(());
        }

        last_status = format!("mirror {mirror} failed (exit code {:?})", status.code());
        eprintln!("{last_status}");
    }

    Err(format!("All mirrors failed, last error: {last_status}").into())
}

/// Resolves the Gradle launcher, erroring out when it is not on PATH.
async fn resolve_gradle() -> Result<&'static str, Box<dyn std::error::Error>> {
    if Command::new("gradle")
        .arg("--version")
        .output()
        .await
        .is_ok()
    {
        return Ok("gradle");
    }
    Err("gradle not found on PATH.".into())
}

/// Coordinates without a version (`group:artifact`) resolve to the newest
/// available version.
fn with_version(coordinate: &str) -> String {
    if coordinate.matches(':').count() == 1 {
        format!("{coordinate}:+")
    } else {
        coordinate.to_string()
    }
}

/// Path of the throwaway project used for one mirror attempt.
fn temp_project_dir() -> std::path::PathBuf {
    std::env::temp_dir().join(format!("ayeneh-gradle-{}", std::process::id()))
}

/// Writes the throwaway project that resolves `coordinates` from `mirror`.
fn write_project(dir: &Path, mirror: &str, coordinates: &[String]) -> std::io::Result<()> {
    fs::create_dir_all(dir)?;
    fs::write(
        dir.join("settings.gradle"),
        "rootProject.name = 'ayeneh-mirror-install'\n",
    )?;
    fs::write(dir.join("build.gradle"), build_script(mirror, coordinates))?;
    Ok(())
}

/// Builds the Gradle script used to download `coordinates` from `mirror`:
/// one repository, the requested dependencies, and a `resolveMirror` task
/// that forces artifact resolution (and therefore the download).
fn build_script(mirror: &str, coordinates: &[String]) -> String {
    let dependencies: String = coordinates
        .iter()
        .map(|coordinate| format!("    mirrorDeps '{coordinate}'\n"))
        .collect();

    format!(
        r#"// Generated by ayeneh-cli; deleted after the install attempt.
repositories {{
    maven {{ url = uri('{mirror}') }}
}}

configurations {{
    mirrorDeps {{
        // Java runtime classpath attributes. Without these Gradle cannot
        // select a variant of modules that publish Gradle Module Metadata
        // (e.g. Guava) and resolution fails with "no matching variant".
        canBeConsumed = false
        canBeResolved = true
        attributes {{
            attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_RUNTIME))
            attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, Category.LIBRARY))
            attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(LibraryElements, LibraryElements.JAR))
            attribute(Bundling.BUNDLING_ATTRIBUTE, objects.named(Bundling, Bundling.EXTERNAL))
            attribute(TargetJvmEnvironment.TARGET_JVM_ENVIRONMENT_ATTRIBUTE, objects.named(TargetJvmEnvironment, TargetJvmEnvironment.STANDARD_JVM))
        }}
    }}
}}

dependencies {{
{dependencies}}}

tasks.register('resolveMirror') {{
    def mirrorDeps = configurations.mirrorDeps
    doLast {{
        mirrorDeps.resolve().each {{ file ->
            println "Resolved: ${{file}}"
        }}
    }}
}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::{build_script, with_version};

    #[test]
    fn script_targets_mirror_and_coordinates() {
        let script = build_script(
            "https://repo1.maven.org/maven2/",
            &["com.google.guava:guava:34.0.0-jre".to_string()],
        );

        assert!(script.contains("maven { url = uri('https://repo1.maven.org/maven2/') }"));
        assert!(script.contains("mirrorDeps 'com.google.guava:guava:34.0.0-jre'"));
        assert!(script.contains("attribute(Usage.USAGE_ATTRIBUTE"));
        assert!(script.contains("tasks.register('resolveMirror')"));
    }

    #[test]
    fn coordinates_without_version_resolve_latest() {
        assert_eq!(
            with_version("com.google.guava:guava"),
            "com.google.guava:guava:+"
        );
        assert_eq!(
            with_version("com.google.guava:guava:34.0.0-jre"),
            "com.google.guava:guava:34.0.0-jre"
        );
    }
}
